### PR TITLE
Merge Upstream Patch To 3.4.113

### PR DESCRIPTION
**Pull request by Nicklas373**
I already upstream this kernel to latest revision in 3.4.y (3.4.113) from 3.4.0, I hope you can merge this change to update flamingo.

I already test this patch, no problem so far in a week test. First commit is for remove warning in gcc compile, after that is update for upstream.

### CODE REVIEW

**Comment by rmnhg** [comment]
Thank you very much for your work! I will try on my phone and, if it goes well, I will merge.
Thanks again :)

**Comment by Nicklas373** [comment]
Okay, thanks for your response :). I'll looking forward your reply :)

**Comment by Nicklas373** [comment]
i already fix kernel compilation again, sorry for long time response about patch. I don't know about that error, @infus38 is reported about that problem. And now flamingo already finish to compile :D

**Comment by Nicklas373** [comment]
I close this pull request because i don't know how is unknown commit is following to pull too, i already make a new pull request without that commit c9cf0c6

**Pull request closed without merging**
